# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff1cc592b7a593f1ecc627559c2f3d7fa62d36c59925fee06493f6b97d34413dec65ac62c8f436d366a41fead9127f11ab45b1e7830039b98915e9a8603ccd7d

test:
  secret_key_base: 9a63d6b8b70a435076dddbc63df386c45b644ef99eab0d30b39ac36b5f037a853da81ad8545732240de5f2953db23951228c51c7872fcc8b09f9dc3ed5e59b8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
